### ISSUE TITLE
Token misrepresented in token dropdown

### ISSUE THREAD

**Issue by yosefromano** [sgladstone/com.fountaintribe.familyfriendly#2]
Big fan of this extension!

One of the greetings is labeled as "Mr. and Mrs. Michael Klein" (see attached) but prints Mr. Michael Klein and Mrs. _Jane_ Klein
it's this token: {greetings.joint_formal_firstname}

![screen shot 2017-03-07 at 12 36 43 pm](https://cloud.githubusercontent.com/assets/10218159/23676832/d2f72ff6-0332-11e7-8bb7-d26ba21d5598.png)

**Comment by sgladstone** [comment]
I am not able to reproduce this issue.  Can you double check that the last names are identical, ie no extra spaces, non-printable characters, etc. in the last_name field in your database.

**Comment by yosefromano** [comment]
The last names are identical. 
The issue is resolved when I assign the wife the gender female.
This is as long as the wife's prefix is Mrs. (I didn't try with Dr. orMs. or Miss) but if it is custom like Rabbi, it doesn't resolve even if the gender is set.
It did not resolve when I assigned the Male with gender male regardless of the prefix.

Thanks!!!

**Comment by sgladstone** [comment]
There is now documentation on current behavior at: https://github.com/sgladstone/com.pogstone.fancytokens/wiki/Joint-greeting-examples   

(Please note: these token issues should be filed on a different extension, ie https://github.com/sgladstone/com.pogstone.fancytokens)

**Comment by sgladstone** [comment]
I tried your scenario (husband has a title, wife has no title, wife has gender filled in as female,  and last names are identical) and I get what I expected:
 Dr. and Mrs. Kevin Jones

so I cannot reproduce your issue,

**Comment by yosefromano** [comment]
Thanks for the quick replies
The scenario is Husband has title, wife has title, no-one or husband has gender filled
