### ISSUE TITLE
Not all tokens put the man first

### ISSUE THREAD

**Issue by yosefromano** [sgladstone/com.fountaintribe.familyfriendly#3]
I did some testing,
It seems that some tokens will always put the man first (meaning Mr. and Mrs. rather than Mrs. and Mr.) regardless of which contact is contact_a in the relationship. 

{greetings.joint_formal} and {greetings.joint_casual}   always put the man first but the other tokens will put the woman first if she is contact_a in the relationship

Would be nice to have all the tokens put the man as contact_a 
Also in the couples - household search, would be nice if the man was always contact_a

**Comment by sgladstone** [comment]
Is there an etiquette guide that indicates this rule of who to list first for a couple? 

With the formal greetings ( eg Mr. and Mrs Smith,  or  Dr. and Mr Jones or Dr. and Dr. Kaplan) the rules ( ie those found at emilypost.com) are more nuanced. If no one has a title, then Mr. goes first.  If one person has a title, then the titled person goes first, such as Dr. and Mr.  If both people have a title, then  the more senior title goes first. In my token, I have no way of determining the more senior title( ie Dr. and Major Smith) so in this case, my token does not impose an order.

**Comment by sgladstone** [comment]
In the "household search", if you filter on membership then the primary member will be listed first.

**Comment by sgladstone** [comment]
A detailed guide that I relied on when developing the joint tokens: http://emilypost.com/advice/guide-to-addressing-correspondence/

**Comment by sgladstone** [comment]
Also review the documentation at: https://github.com/sgladstone/com.pogstone.fancytokens/wiki/Joint-greeting-examples
